management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info
security:
    jwt:
        secret: ${JWT_SECRET}
server:
    port: ${PORT}
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USER}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    mvc:
        format:
            date: ISO
springdoc:
    swagger-ui:
        url: openapi.yaml
aws:
    s3:
        bucket-name: ${AWS_S3_REPORT_BUCKET}
        region: ${AWS_REGION}
        template-bucket-name: ${AWS_S3_TEMPLATE_BUCKET}
    credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
templates:
    pdf: ${PDF_TEMPLATE}